#!/usr/bin/env bash

# Define package groups as arrays. Feel free to add/remove groups.
BASE_PACKAGES=(
	base-devel
	foot
	noto-fonts
	nvim
	openssh
	pipewire
	pipewire-jack
	polkit
	qt6-multimedia-ffmpeg
	sddm
	starship
	stow
	thunar
	ttf-firacode-nerd
	ttf-font-nerd
	uwsm
	xdg-desktop-portal
	zsh
)

HYPERLAND_PACKAGES=(
	hyprland
	hyprpaper
	hyprpolkitagent
	mako
	waybar
	xdg-desktop-portal-hyprland
)

# Merge arrays into PACKAGES. Order matters; duplicates will be removed later.
PACKAGES=(
	"${BASE_PACKAGES[@]}"
	"${HYPERLAND_PACKAGES[@]}"
)

AUR_PACKAGES=(
	# Add AUR packages here if needed
)